; PlatformIO Project Configuration File
;
; Teensy 4.1 - 12-Channel Logic Analyzer
; Build:            pio run
; Upload to board:  pio run -t upload
; Serial monitor:   pio device monitor

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
; monitor_port = /dev/cu.usbmotem203421801
monitor_speed = 115200
upload_protocol = teensy-cli
build_flags =
    -O2
